from Execution import run
import threading 

t1=threading.Thread(target=run, args=('competition_01.txt',))
t2=threading.Thread(target=run, args=('competition_02.txt',))
t3=threading.Thread(target=run, args=('competition_03.txt',))
t4=threading.Thread(target=run, args=('competition_04.txt',))
t5=threading.Thread(target=run, args=('competition_05.txt',))
t6=threading.Thread(target=run, args=('competition_06.txt',))
t7=threading.Thread(target=run, args=('competition_07.txt',))
t8=threading.Thread(target=run, args=('competition_08.txt',))
t9=threading.Thread(target=run, args=('competition_09.txt',))
t10=threading.Thread(target=run, args=('competition_10.txt',))
t11=threading.Thread(target=run, args=('competition_11.txt',))
t12=threading.Thread(target=run, args=('competition_12.txt',))
t13=threading.Thread(target=run, args=('competition_13.txt',))
t14=threading.Thread(target=run, args=('competition_14.txt',))
t15=threading.Thread(target=run, args=('competition_15.txt',))
t1.start()
t2.start()
t3.start()
t4.start()
t5.start()
t6.start()
t7.start()
t8.start()
t9.start()
t10.start()
t11.start()
t12.start()
t13.start()
t14.start()
t15.start()
t1.join()
t2.join()
t3.join()
t4.join()
t5.join()
t6.join()
t7.join()
t8.join()
t9.join()
t10.join()
t11.join()
t12.join()
t13.join()
t14.join()
t15.join()
